### ISSUE TITLE
請問出現這個錯誤 要怎除錯呢 謝謝

### ISSUE THREAD

**Issue by radius1220** [meiu/meiupic#38]
Warning: PDO::__construct(): Server sent charset (255) unknown to the client. Please, report to the developers in /home/bblensco/public_html/meiupic3/core/driver/db/pdomysql.php on line 87

Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000] [2054] Server sent charset unknown to the client. Please, report to the developers' in /home/bblensco/public_html/meiupic3/core/driver/db/pdomysql.php:87 Stack trace: #0 /home/bblensco/public_html/meiupic3/core/driver/db/pdomysql.php(87): PDO->__construct('mysql:host=loca...', 'bbco_pic', 'picpic@111') #1 /home/bblensco/public_html/meiupic3/core/driver/db/pdomysql.php(144): DBPdomysql->connect() #2 /home/bblensco/public_html/meiupic3/core/class/db.class.php(192): DBPdomysql->query('SELECT name,val...') #3 /home/bblensco/public_html/meiupic3/apps/base/base.class.php(183): DB->getAssoc() #4 /home/bblensco/public_html/meiupic3/core/core.php(580): BaseClass->getAllSettings() #5 /home/bblensco/public_html/meiupic3/index.php(17): run() #6 {main} thrown in /home/bblensco/public_html/meiupic3/core/driver/db/pdomysql.php on line 87

**Comment by radius1220** [comment]
資料庫伺服器
伺服器： Localhost via UNIX socket
伺服器類型： MySQL
伺服器連線： 未有使用 SSL 說明文件
伺服器版本： 8.0.30 - MySQL Community Server - GPL
協定版本： 10
使用者： bblensco@localhost
伺服器字元集： UTF-8 Unicode (utf8mb4)

網頁伺服器
cpsrvd 11.104.0.8
資料庫用戶端版本： libmysql - mysqlnd 7.4.30
PHP 擴充套件： mysqli說明文件 curl說明文件 mbstring說明文件
PHP 版本： 7.4.30

 伺服器連線編碼
utf8mb4_unicode_ci
